Update update-animation.yml

diff --git a/.github/workflows/update-animation.yml b/.github/workflows/update-animation.yml
--- a/.github/workflows/update-animation.yml
+++ b/.github/workflows/update-animation.yml
@@ -3,7 +3,7 @@ name: Update Animation in README
 on:
   workflow_dispatch:
   schedule:
-    - cron: "0 */2 * * *"  # Executa a cada 2 horas
+    - cron: "0 */2 * * *"
 
 jobs:
   update-animation:
@@ -23,6 +23,16 @@ jobs:
           pwd
           echo "Files in directory:"
           ls -la
+
+      - name: Debug update-animation.py
+        run: |
+          if [ -f "update-animation.py" ]; then
+            echo "update-animation.py content:"
+            cat update-animation.py
+          else
+            echo "update-animation.py not found."
+            exit 1
+          fi
 
       - name: Install dependencies (if requirements.txt exists)
         run: |
