Update update-gif.yml

diff --git a/.github/workflows/update-gif.yml b/.github/workflows/update-gif.yml
--- a/.github/workflows/update-gif.yml
+++ b/.github/workflows/update-gif.yml
@@ -28,7 +28,12 @@ jobs:
 
       - name: Run update GIF script
         run: |
-          python .github/workflows/update-gif/update_gif.py
+          if [ -f ".github/workflows/update-gif/update_gif.py" ]; then
+            python .github/workflows/update-gif/update_gif.py
+          else
+            echo "Script update_gif.py not found. Please check the path and try again."
+            exit 1
+          fi
 
       - name: Commit and push changes
         run: |
